Filename: Create Release Versions.yml

# Name of the Workflow
name: Create Release Versions

# Run on every commit tag which begins with “v” (e.g., “v0.1.4”)
on:
  push: 
    tags:
      - “v*”
    workflow_dispatch:
    inputs:
      environment:
      description: 'Re-run Action'
      required: true
      default: 'Re-run Action'
      type: choice
      options:
        - Re-run Action
        
# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release:
    name: “Create Release Versions”
    runs-on: “ubuntu-latest”
    steps:
      - uses: “marvinpinto/action-automatic-release@latest”
        with: 
        repo_token: "${{ secrets.GITHUB_TOKEN }}”
        prerelease: false
